### ISSUE TITLE
tessting on Rails 4

### ISSUE THREAD

**Issue by victorsosa** [mahinder/rails_handsontable#6]
Hi, 

I am testing this on Rails 4 and got this issue in the JS console.

error
```
TypeError: rootElement is null 
```

handsontable code 
```
  this.rootElement = rootElement;

  this.container = document.createElement('DIV');
  this.container.className = 'htContainer';

  rootElement.insertBefore(this.container, rootElement.firstChild);
```

**Comment by victorsosa** [comment]
I needed to wrap between a $(function() {})

**Comment by mahinder** [comment]
Sorry for not reply , i was stuck in some work so not get chance to look this.
Thanks for solving issue , can you tell me how you solve issue that will helpful for me to update gem.

Thanks once again

**Comment by victorsosa** [comment]
Like I said: I needed to wrap between a $(function() { "code goes here...."})
