### ISSUE TITLE
rubygems version issue

### ISSUE THREAD

**Issue by victorsosa** [mahinder/rails_handsontable#8]
HI,

I am trying to update the gem to last version 0.13.1, but the bundle command and the rubygems site still pointing to the old 0.1.5.

Can you fix that please?

**Comment by mahinder** [comment]
HI,

Can you please explain me what exact we need here , and you are trying .


Thanks,
Mahinder

**Comment by mahinder** [comment]
I Updates version to 0.13.1 , please take a look and let me now i understand your requirement same or not.

**Comment by victorsosa** [comment]
never mind, I did bundle update and it works perfect
